apiVersion: v1
kind: Pod
metadata:
  name: pytorch-lightning-pod
spec:
  containers:
    - name: pytorch-container
      image: ccu-k8s.inf.uni-konstanz.de:32250/carmely.reiska/extended-nas-t:latest
      command: ["sleep", "1d"]
      resources:
        requests:
          cpu: 1
          nvidia.com/gpu: 1
          memory: 10Gi
        limits:
          cpu: 1
          nvidia.com/gpu: 1
          memory: 10Gi
      volumeMounts:
        - mountPath: /abyss/home
          name: cephfs-home
          readOnly: false
        - mountPath: /abyss/shared
          name: cephfs-shared
          readOnly: false
        - mountPath: /abyss/datasets
          name: cephfs-datasets
          readOnly: true
  imagePullSecrets:
  - name: ccu-registry-secret
  volumes:
    - name: cephfs-home
      hostPath:
        path: "/cephfs/abyss/home/carmely-reiska"
        type: Directory
    - name: cephfs-shared
      hostPath:
        path: "/cephfs/abyss/shared"
        type: Directory
    - name: cephfs-datasets
      hostPath:
        path: "/cephfs/abyss/datasets"
        type: Directory

